# Generated by Django 4.1.1 on 2022-12-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_adverts_category_commentproduct_customeruser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplocation',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='shoplocation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='standard.shoplocation'),
        ),
    ]
