# Generated by Django 4.1.1 on 2022-12-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_remove_shoplocation_vendor_id_vendor_shoplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
