# Generated by Django 4.1.1 on 2022-12-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_order_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertsPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(max_length=900)),
                ('short_description', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.vendor')),
            ],
        ),
    ]
