# Generated by Django 4.1.1 on 2022-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_advertspro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertspro',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_img_url',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='identification_img_url',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shop_img_url',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user_img',
        ),
        migrations.AddField(
            model_name='advertspro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='cust_img',
            field=models.ImageField(blank=True, null=True, upload_to='customers'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='identification_img',
            field=models.ImageField(blank=True, null=True, upload_to='Ven_ID'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_img',
            field=models.ImageField(blank=True, null=True, upload_to='Shop_img'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(default='EGP', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_type',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commercial_registration',
            field=models.ImageField(blank=True, null=True, upload_to='Ven_com_register'),
        ),
        migrations.DeleteModel(
            name='Adverts',
        ),
    ]
